version: 0.2

env:
    variables:
        AWS_REGION_2: "us-west-2"
        REACT_APP_API_SERVICE_URL: "http://flask-react-alb-1739523387.us-east-1.elb.amazonaws.com"

phases:
    install:
        runtime-versions:
            docker: 18
    pre_build:
        commands:
            - docker login -u $dockerhub_username -p $dockerhub_password
            - echo logging in to ecr...
            - >
                aws ecr get-login-password --region $AWS_REGION \
                  | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
    build:
        commands:
            - echo building dev images...
            - echo building prod images...
            - >
                docker build \
                  -f uberbackend/Dockerfile \
                  -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/uber-be:prod \
                  ./uberbackend
            - >
                docker build \
                  -f uberfrontend/Dockerfile \
                  -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/uber-fe:prod \
                  --build-arg NODE_ENV=production \
                  --build-arg REACT_APP_API_SERVICE_URL=$REACT_APP_API_SERVICE_URL \
                  ./uberfrontend
    post_build:
        commands:
            - echo pushing prod images to ecr...
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/uber-be:prod
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/uber-fe:prod
